### ISSUE TITLE
Clarification on schematics

### ISSUE THREAD

**Issue by Tony-1234** [charcole/TeensyJVS#2]
Could you please advise what RS485 transceiver you are using (MAX485?) and what diodes between sense line and GND?

**Comment by charcole** [comment]
The RS485 were these sorts of modules if I remember correctly http://www.ebay.co.uk/itm/5-MAX485-Module-RS485-Module-TTL-RS-485-Module-Converter-Board-For-Arduino-5V-FK-/232181622279?hash=item360f1a6607:g:SncAAOSw44BYWogX. Diodes were just some generic small signal diodes. I can't read the number off them but I measure a 0.7V forward drop. Hope that helps.

**Comment by Tony-1234** [comment]
Thanks for the quick response. What about the polarity of those diodes? I'm not quite sure if I understood how that sense line circuit works...

**Comment by charcole** [comment]
Diodes a forward biased (ie. they allow current to flow to ground). From what I remember the sense line provides 3 different states. The upstream device has a pull up to 5V. When nothing is connected it reads 5V, when a device is connected the diodes pull down that voltage to about 3V and finally when the device is registered the micro controller pulls the line down to zero volts. JVS devices are designed to be chained together and the sense line allows them to be assigned IDs automatically. Check the links in the README for more information.
